### ISSUE TITLE
Where is README and the complete code?

### ISSUE THREAD

**Issue by Desperado721** [bisheng/KTG4KBQG#1]
Hi, 

Thank you for sharing your code. I am interested in your work. Could you update the README along with the complete code?
Thank you

**Comment by salvatoreferragamo** [comment]
Same question. Where is the complete codes?

**Comment by Yukyin** [comment]
Same question. Where is the complete codes?

**Comment by PersistenceForever** [comment]
Same question. Where is the complete codes?

**Comment by bisheng** [comment]
Thank you for your attention, and the original code has been modified for another paper. We will release complete codes after we get the results.

**Comment by ysgncss** [comment]
Hi, Could you upload the complete code?
